# Generated by Django 2.2.10 on 2020-03-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('pub_date', models.DateField(null=True, verbose_name='发布日期')),
                ('bread', models.IntegerField(default=0, verbose_name='阅读量')),
                ('comment', models.IntegerField(default=0, verbose_name='评论量')),
                ('Content', models.TextField(default='', verbose_name='文章内容')),
            ],
        ),
    ]
