# Generated by Django 2.2.10 on 2020-03-02 12:01

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Content',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(default=0),
        ),
    ]
