# Generated by Django 2.2.10 on 2020-03-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200302_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
    ]
